/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "prot.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <getopt.h>

#include <protRelayUtil.h>

static CLIENT              *clnt = 0;
static struct sockaddr_in   clntAddr;

const struct sockaddr_in *
getRssibMapClntAddr()
{
	if ( ! clnt ) {
		printErrMsg( "ERROR: getRssiMapAddr() -- client not created yet\n" );
		return 0;
	}
	return &clntAddr;
}

CLIENT *
getRssibMapClnt()
{
	return clnt;
}

CLIENT *
createRssibMapClnt(const char *group, unsigned short port)
{
	clntAddr.sin_family      = AF_INET;
	clntAddr.sin_addr.s_addr = inet_addr( group );
	clntAddr.sin_port        = htons( port );

	clnt = mkMcClnt( &clntAddr, RSSIB_MAP, RSSIB_MAP_V0 );

	return clnt;
}
