/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROT_H_RPCGEN
#define _PROT_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct PortDesc {
	short portNum;
	bool_t hasRssi;
};
typedef struct PortDesc PortDesc;

struct MapReq {
	int ipAddr;
	struct {
		u_int ports_len;
		struct PortDesc *ports_val;
	} ports;
};
typedef struct MapReq MapReq;

struct AddArgs {
	int a;
	int b;
};
typedef struct AddArgs AddArgs;

struct McAddr {
	int ipaddr;
	int portno;
};
typedef struct McAddr McAddr;

#define RSSIB_REL 0x40cafe00
#define RSSIB_REL_V0 0

#if defined(__STDC__) || defined(__cplusplus)
#define RSSIB_REL_ECHO 0
extern  enum clnt_stat rssib_rel_echo_0(void *, void *, CLIENT *);
extern  bool_t rssib_rel_echo_0_svc(void *, void *, struct svc_req *);
#define RSSIB_REL_GETMCPORT 1
extern  enum clnt_stat rssib_rel_getmcport_0(void *, struct McAddr *, CLIENT *);
extern  bool_t rssib_rel_getmcport_0_svc(void *, struct McAddr *, struct svc_req *);
#define RSSIB_REL_LKUP 2
extern  enum clnt_stat rssib_rel_lkup_0(struct MapReq *, struct MapReq *, CLIENT *);
extern  bool_t rssib_rel_lkup_0_svc(struct MapReq *, struct MapReq *, struct svc_req *);
extern int rssib_rel_0_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RSSIB_REL_ECHO 0
extern  enum clnt_stat rssib_rel_echo_0();
extern  bool_t rssib_rel_echo_0_svc();
#define RSSIB_REL_GETMCPORT 1
extern  enum clnt_stat rssib_rel_getmcport_0();
extern  bool_t rssib_rel_getmcport_0_svc();
#define RSSIB_REL_LKUP 2
extern  enum clnt_stat rssib_rel_lkup_0();
extern  bool_t rssib_rel_lkup_0_svc();
extern int rssib_rel_0_freeresult ();
#endif /* K&R C */

#define RSSIB_MAP 0x40cafe01
#define RSSIB_MAP_V0 0

#if defined(__STDC__) || defined(__cplusplus)
#define RSSIB_MAP_ECHO 0
extern  enum clnt_stat rssib_map_echo_0(void *, void *, CLIENT *);
extern  bool_t rssib_map_echo_0_svc(void *, void *, struct svc_req *);
#define RSSIB_MAP_LKUP 1
extern  enum clnt_stat rssib_map_lkup_0(struct MapReq *, struct MapReq *, CLIENT *);
extern  bool_t rssib_map_lkup_0_svc(struct MapReq *, struct MapReq *, struct svc_req *);
extern int rssib_map_0_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RSSIB_MAP_ECHO 0
extern  enum clnt_stat rssib_map_echo_0();
extern  bool_t rssib_map_echo_0_svc();
#define RSSIB_MAP_LKUP 1
extern  enum clnt_stat rssib_map_lkup_0();
extern  bool_t rssib_map_lkup_0_svc();
extern int rssib_map_0_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_PortDesc (XDR *, PortDesc*);
extern  bool_t xdr_MapReq (XDR *, MapReq*);
extern  bool_t xdr_AddArgs (XDR *, AddArgs*);
extern  bool_t xdr_McAddr (XDR *, McAddr*);

#else /* K&R C */
extern bool_t xdr_PortDesc ();
extern bool_t xdr_MapReq ();
extern bool_t xdr_AddArgs ();
extern bool_t xdr_McAddr ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROT_H_RPCGEN */
