/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prot.h"

#include <arpa/inet.h>

bool_t
rssib_map_echo_0_svc(void *argp, void *result, struct svc_req *rqstp)
{
	/* PING */
	return 1;
}

bool_t
rssib_map_lkup_0_svc(struct MapReq *argp, struct MapReq *result, struct svc_req *rqstp)
{
	const char *num = getenv("NUM");

	result->ports.ports_len = 0;
	result->ports.ports_val = 0;

	if ( ! num )
		return 0;

	struct in_addr me;
	struct in_addr you;

	me.s_addr  = inet_addr(num);

	you.s_addr = htonl(argp->ipAddr);

	printf("LKUP (MAP) - checking %s == %s\n", num, inet_ntoa(you));

	if ( me.s_addr == you.s_addr ) {
		result->ipAddr = argp->ipAddr;
		result->ports.ports_len            = 1;
		result->ports.ports_val = mem_alloc( sizeof(result->ports.ports_val[0])*result->ports.ports_len );
		result->ports.ports_val[0].hasRssi = 0;
		result->ports.ports_val[0].portNum = 44;

		printf("LKUP (MAP) OK\n");
		return 1;
	}

	return 0;
}

int
rssib_map_0_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
