/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "prot.h"

bool_t
xdr_PortDesc (XDR *xdrs, PortDesc *objp)
{
	 if (!xdr_short (xdrs, &objp->portNum))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->hasRssi))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MapReq (XDR *xdrs, MapReq *objp)
{
	 if (!xdr_int (xdrs, &objp->ipAddr))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->ports.ports_val, (u_int *) &objp->ports.ports_len, ~0,
		sizeof (PortDesc), (xdrproc_t) xdr_PortDesc))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AddArgs (XDR *xdrs, AddArgs *objp)
{
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_McAddr (XDR *xdrs, McAddr *objp)
{
	 if (!xdr_int (xdrs, &objp->ipaddr))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->portno))
		 return FALSE;
	return TRUE;
}
