/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "prot.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <getopt.h>

#include <protRelayUtil.h>

#include "protMap_svc.c"

#include <rpcMapService.h>

SVCXPRT *
rpcMapServer(struct sockaddr_in *mcsa, in_addr_t ipAddr, PortMap *maps, unsigned numMaps)
{
SVCXPRT            *transp = 0;
SVCXPRT            *rval   = 0;

int                 mcsd;

	setPortMaps( ipAddr, maps, numMaps );

	if ( (mcsd = mkMcSd(1, mcsa)) < 0 ) {
		fprintf(stderr, "ERROR: Unable to create multicast socket for SVC\n");
		goto bail;
	}

	transp = svcudp_create( mcsd );
	if ( ! transp ) {
		fprintf(stderr, "Unable to create UDP MAP RPC service\n");
		goto bail;
	}

	if ( ! svc_register(transp, RSSIB_MAP, RSSIB_MAP_V0, rssib_map_0, 0) ) {
		fprintf(stderr, "Unable to register RSSIB_MAP(V0) service\n");
		goto bail;
	}

	rval   = transp;
	transp = 0;

bail:
	if ( transp ) {
		svc_destroy( transp );
	}

	return rval;
}
